CREATE TABLE IF NOT EXISTS Users(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(255),
    password VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS Post(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(255),
    salary INTEGER
);

CREATE TABLE IF NOT EXISTS Workers(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(255),
    surname VARCHAR(255),
    post_id INTEGER,
    FOREIGN KEY (post_id) REFERENCES Post(id)
);

CREATE TABLE IF NOT EXISTS Menu(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(255),
    price INTEGER
);

CREATE TABLE IF NOT EXISTS Orders(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    menu_id INTEGER,
    user_id INTEGER,
    FOREIGN KEY (menu_id) REFERENCES Menu(id),
    FOREIGN KEY (user_id) REFERENCES Users(id)
);

CREATE TABLE IF NOT EXISTS Cafe(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(255),
    address VARCHAR(255),
    telephone_number INTEGER
);