# Form implementation generated from reading ui file 'logWin.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(290, 390, 221, 80))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.OKButton = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.OKButton.setObjectName("OKButton")
        self.gridLayout.addWidget(self.OKButton, 0, 0, 1, 1)
        self.CancelButton = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.CancelButton.setObjectName("CancelButton")
        self.gridLayout.addWidget(self.CancelButton, 0, 1, 1, 1)
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(610, 180, 160, 181))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Admin = QtWidgets.QRadioButton(parent=self.verticalLayoutWidget)
        self.Admin.setObjectName("Admin")
        self.verticalLayout.addWidget(self.Admin)
        self.Worker = QtWidgets.QRadioButton(parent=self.verticalLayoutWidget)
        self.Worker.setObjectName("Worker")
        self.verticalLayout.addWidget(self.Worker)
        self.User = QtWidgets.QRadioButton(parent=self.verticalLayoutWidget)
        self.User.setObjectName("User")
        self.verticalLayout.addWidget(self.User)
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(210, 120, 441, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(290, 230, 221, 96))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.Login = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget_2)
        self.Login.setObjectName("Login")
        self.verticalLayout_2.addWidget(self.Login)
        self.label_3 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.Password = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget_2)
        self.Password.setObjectName("Password")
        self.verticalLayout_2.addWidget(self.Password)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Окно входа"))
        self.OKButton.setText(_translate("MainWindow", "ОК"))
        self.CancelButton.setText(_translate("MainWindow", "Отмена"))
        self.Admin.setText(_translate("MainWindow", "Администратор"))
        self.Worker.setText(_translate("MainWindow", "Работник"))
        self.User.setText(_translate("MainWindow", "Пользователь"))
        self.label.setText(_translate("MainWindow", "Введите имя и пароль аккаунта и выберите роль"))
        self.label_2.setText(_translate("MainWindow", "Логин"))
        self.label_3.setText(_translate("MainWindow", "Пароль"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
